import json
from abc import ABC, abstractmethod

from core.config.settings import Settings, get_settings
from core.models.domain import AIEnrichment, ThreatEvent


class AIProvider(ABC):
    @abstractmethod
    async def enrich(self, event: ThreatEvent) -> AIEnrichment:
        raise NotImplementedError


class DeterministicProvider(AIProvider):
    async def enrich(self, event: ThreatEvent) -> AIEnrichment:
        cves = ", ".join(cve.cve_id for cve in event.cves) or "no CVEs"
        return AIEnrichment(
            executive_summary=f"{event.title} is assessed as {event.severity} with {event.confidence}% confidence.",
            technical_analysis=event.description,
            affected_assets=[product for cve in event.cves for product in cve.affected_products],
            mitre_attack=[],
            recommendations=["Patch affected systems", "Hunt for listed indicators", "Review exposed services"],
            detection_opportunities=[f"Monitor telemetry related to {cves}"],
            analyst_notes=["Generated by deterministic fallback provider"],
            confidence_explanation=(
                "Confidence combines source reputation, corroboration, indicators, and exploitation evidence."
            ),
        )


class OpenAIProvider(DeterministicProvider):
    def __init__(self, settings: Settings) -> None:
        self.settings = settings


class GeminiProvider(DeterministicProvider):
    def __init__(self, settings: Settings) -> None:
        self.settings = settings


class AnthropicProvider(DeterministicProvider):
    def __init__(self, settings: Settings) -> None:
        self.settings = settings


class EnrichmentService:
    def __init__(self, provider: AIProvider | None = None) -> None:
        self.provider = provider or self._provider_from_settings(get_settings())

    async def enrich(self, event: ThreatEvent) -> ThreatEvent:
        event.enrichment = await self.provider.enrich(event)
        return event

    def _provider_from_settings(self, settings: Settings) -> AIProvider:
        if settings.openai_api_key:
            return OpenAIProvider(settings)
        if settings.gemini_api_key:
            return GeminiProvider(settings)
        if settings.anthropic_api_key:
            return AnthropicProvider(settings)
        return DeterministicProvider()


def parse_structured_json(payload: str) -> AIEnrichment:
    return AIEnrichment.model_validate(json.loads(payload))
